# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  boot.initrd.supportedFilesystems = [ "btrfs" ];
  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "acpi_call" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ acpi_call ];
  boot.initrd.luks.devices."vega_crypt".device =
    "/dev/disk/by-label/VEGA_CRYPT";

  fileSystems."/" = {
    device = "/dev/disk/by-label/VEGA_BTRFS";
    fsType = "btrfs";
    options = [ "subvol=root" "noatime" "compress=zstd" "space_cache=v2" ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-label/VEGA_BTRFS";
    fsType = "btrfs";
    options = [ "subvol=swap" "noatime" "nodatacow" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-label/VEGA_BTRFS";
    fsType = "btrfs";
    options = [ "subvol=nix" "noatime" "compress=zstd" "space_cache=v2" ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-label/VEGA_BTRFS";
    fsType = "btrfs";
    options = [ "subvol=persist" "noatime" "compress=zstd" "space_cache=v2" ];
    neededForBoot = true;
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-label/SYSTEM_DRV";
    fsType = "vfat";
  };

  swapDevices = [{
    device = "/swap/swapfile";
    size = 32768;
  }];
  nixpkgs.hostPlatform.system = "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
